### ISSUE TITLE
accessToken is null after loging in

### ISSUE THREAD

**Issue by MikaelSpinnangr** [OpenForma/Formicae#19]
![image](https://github.com/OpenForma/Formicae/assets/89906534/1cf69cb6-76a5-4f70-9af8-f5e96890e10b)
Even though i see i have a value in debug 
![image](https://github.com/OpenForma/Formicae/assets/89906534/cebd04a3-40ad-4e53-ab95-69f7caaadf95)

**Comment by aashkann** [comment]
Does it freeze?

**Comment by MikaelSpinnangr** [comment]
No freezing, just null

**Comment by aashkann** [comment]
I think this might be casued by the internet connection or a firewall or VPN. Try to use it without any of this and let me know.
