### ISSUE TITLE
Automate Simulaiton box generation

### ISSUE THREAD

**Issue by MikaelSpinnangr** [OpenForma/Formicae#21]
Create simulation box based on Buildings and terrain + checks

**Comment by aashkann** [comment]
I just tried Embree wrapper dhart to see if this makes the process of projecting faster and It did. Take a look at arze branch and tell me what you think. Now these two components combines output the postJson in almost 300ms.
![image](https://github.com/OpenForma/Formicae/assets/101568776/e190d58a-b95b-449f-9d51-4e5d38b1996a)
